### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by silviustan** [contributte/live-form-validation#48]
Hi,

I get this error on a regular bootstrap 3 form, Nette 2.4. Every field is wrapped by form-group, nothing special...

Everything happens on this line(306): parentEl.insertBefore(messageEl, el.nextSibling);

```
live-form-validation.js:306 Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at Object.LiveForm.getMessageElement (admin/assets/js/live-form-validation.js:306:13)
    at Object.LiveForm.processServerErrors (admin/assets/js/live-form-validation.js:145:23)
    at Object.Nette.initForm (admin/assets/js/live-form-validation.js:1151:12)
    at HTMLDocument.<anonymous> (admin/assets/js/live-form-validation.js:1165:12)
```
Anybody else? Do you have some suggestions how to fix it?

**Comment by marysmech** [comment]
I have exactly same problem after update to Nette 2.4.
